### ISSUE TITLE
Промяна на изгледа на записите в ателието

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#28]
Предлагам да се направи подравняване отляво на текстовете и полетата. Падащото меню за „Етап“ да се промени по подобие на „Преглед“.
При „Работа в екип“ изгледът на коментарите (Следните потребители обработват текста:) да се промени по подобие на „Читателски мнения“.
![chitanka-004](https://f.cloud.github.com/assets/1268290/1826552/ad914574-7200-11e3-9c55-833605f7a06f.png)
![chitanka-005](https://f.cloud.github.com/assets/1268290/1826553/b2835d9c-7200-11e3-9356-fa2a1be8414d.png)
Не знам дали е възможно срещу полето „Файл“ да се смени формата за качване с един бутон „Качи“ (или нещо подобно) и да се махне “Browse… No file selected”.

**Comment by bmanolov** [comment]
Ще се направи при обновяването на ателието.
