### ISSUE TITLE
Подравняване на обектите в „Препоръчано“

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#29]
В http://chitanka.info/featured-books да се подравнят всички обекти да бъдат подравнени, защото в момента всички обекти „шават нагоре-надолу“:
![chitanka-006](https://f.cloud.github.com/assets/1268290/1826562/01174ae0-7201-11e3-861a-1b5163939750.png)

**Comment by bmanolov** [comment]
Дреболия.
