### ISSUE TITLE
При използването на облик „Люляк“ се забелязва, че жълтият цвят е преобладаващ

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#35]
![chitanka-013](https://f.cloud.github.com/assets/1268290/1826628/1c005de0-7203-11e3-80d4-de4fd6b995af.png)
Трябва да се нормализира спрямо основния цвят (освен ако умишлено не е оставено така).

**Comment by bmanolov** [comment]
Дреболия.
