### ISSUE TITLE
Промяна на изгледа на „Съдържание“

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#36]
В http://chitanka.info/rules, http://chitanka.info/links и http://chitanka.info/about изгледът за съдържанието може да промени по подобие на съдържанието за произведенията (старо/ново):
![chitanka-014](https://f.cloud.github.com/assets/1268290/1826635/65d2da2e-7203-11e3-89a6-effd9105822d.png)
![chitanka-015](https://f.cloud.github.com/assets/1268290/1826637/7e1c868e-7203-11e3-912c-299d047b2fb4.png)
Относно промяната: визирам заоблените краища и шрифт на текста.

**Comment by bmanolov** [comment]
Дреболия.
