### ISSUE TITLE
Замяна на сегашните бутони в началната страница с 2d бутони с максимално изчистен изглед

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#38]
За подобряване на общия изглед на библиотеката е най-добре да се заменят сегашните 3d бутони в началната страница с 2d бутони с максимално изчистен изглед:
![chitanka-017](https://f.cloud.github.com/assets/1268290/1826653/27863d1e-7204-11e3-9567-5d6e2c2566c4.png)
Това, което се сещам е вместо сегашните 3d бутони да бъдат поставени на тяхно място обикновени бутони по подобие на тези в [сайта на Piwik](http://piwik.org/). За съжаление на видях подходяща иконка в [fontawesome](http://fontawesome.io/icons/).

**Comment by bmanolov** [comment]
Няма кой да го свърши.
