### ISSUE TITLE
Разширяване на полето за коментар в административния панел

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#42]
Полето, което в момента се зарежда е много малко като размер и почти всеки път се налага да бъде разтегляно, за да се появи целия коментар:
![workroom_12](https://f.cloud.github.com/assets/1268290/1844299/4b574670-7515-11e3-8a0f-75f9a1a2db85.png)
Мисля че е достатъчно прозорецът да бъде 501x255 по подразбиране:
![workroom_13](https://f.cloud.github.com/assets/1268290/1844300/e8f3d524-7515-11e3-8726-f455068491db.png)

**Comment by bmanolov** [comment]
Дреболия.
