### ISSUE TITLE
Неправилно показване на страниците в списъка „Подготвяни текстове“ за даден потребител

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#43]
Ако се влезе в страницата на [Диан Жон](http://chitanka.info/user/%D0%94%D0%B8%D0%B0%D0%BD%20%D0%96%D0%BE%D0%BD) и се щракне на 2, 3 или някоя следваща страница, включително и бутона „Следваща“, се зарежда отново същата страница, без да се преминава към следващата страница.
Същото и е при други потребители (напр. [Xesiona](http://chitanka.info/user/Xesiona)).

**Comment by bmanolov** [comment]
Вероятно ще се оправи с новото ателие.
