### ISSUE TITLE
Разлика в големината на иконките за оценка

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#44]
Забелязва се, че има разлика в големината на иконките за оценка:
![chitanka-020](https://f.cloud.github.com/assets/1268290/1859124/1011e162-779d-11e3-8137-cd87392596d5.png)
Предполагам, че иконката, която е за случаите, в които не е дадена оценка, е с по-малък радиус, спрямо другите иконки, които се използват при дадена оценка.

**Comment by bmanolov** [comment]
Дреболия.
