### ISSUE TITLE
Предложение за промяна на позиционирането на търсачката

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#46]
Полето за търсене е изнесено в лявата част на всяка от страниците в библиотеката: 
![search_field_chitanka](https://cloud.githubusercontent.com/assets/1268290/2530492/b98ff29e-b526-11e3-94a6-94dc6046cdb1.png)
Ако е възможно да се направи подобно на: 
![search_field_chitanka_after](https://cloud.githubusercontent.com/assets/1268290/2530497/c9561550-b526-11e3-8cf6-352071717672.png)
Дължината на търсачката може да се разшири, така че да започва от левия ъгъл на „Автори“ (ако теглим вертикална линия) и да стига до десния ъгъл на „Ателие“ (пак по вертикала).

**Comment by bmanolov** [comment]
Дреболия.
