### ISSUE TITLE
Полето за име на потребителя не е съобразена с ширината на името

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#49]
В момента при по-дългите имена се получава припокриване с търсачката (особено при по-малки екрани):
![username-length](https://cloud.githubusercontent.com/assets/1268290/2809403/2a267f24-cd6d-11e3-9f43-f2e135bd176e.png)
Може да се зададе динамична ширина (в зависимост от дължината на потребителското име) на полето.

**Comment by bmanolov** [comment]
Дреболия.
