### ISSUE TITLE
Заглавията на разделите в страничните менюта са с несиметрични полета по вертикала

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#50]
В http://chitanka.info/workroom може да се види за надписите „Работно ателие — Всички“, „Читалня“, „Работилница“, „Колекции“, „Препоръчано“, „Из Мрежата“, че не са центрирани:
![title-bottom-margin](https://cloud.githubusercontent.com/assets/1268290/2809424/80ff41ea-cd6e-11e3-9f8f-a9b0a67c5673.png)
В /bundles/lib/css:1 настройката за това е padding: 0.4em 0px 0.2em;
Може да се промени на padding: 0.4em 0px 0.4em;

**Comment by bmanolov** [comment]
Дреболия.
