### ISSUE TITLE
RSS етикета (на почти всички страници) е „провиснал“ в ъгъла

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#51]
RSS-а може да се изравни, така че да е на едно ниво със заглавието в същата лента. Пример как е в работното ателие:
![title-rss](https://cloud.githubusercontent.com/assets/1268290/2809898/261b65ac-cd8b-11e3-94e9-38ee92847d84.png)

**Comment by bmanolov** [comment]
Дреболия.
