### ISSUE TITLE
Изгледът на съдържание на книга с липсващи произведения не е еднообразно спрямо книги с произведения

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#52]
Пример с http://chitanka.info/book/4852-spisanie-vyrkolak-1998-05:
![book-4852](https://cloud.githubusercontent.com/assets/1268290/2809905/cfa7d18c-cd8b-11e3-959f-3ccca55208aa.png)
Може да се нормализира като http://chitanka.info/book/3696:
![book-3696](https://cloud.githubusercontent.com/assets/1268290/2809909/f66b5d02-cd8b-11e3-975a-fc9845ced48d.png)

**Comment by bmanolov** [comment]
Дреболия.
