### ISSUE TITLE
Уеднаквяване на падащите менюта

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#54]
Полетата за избор (drop-down) в сайта са три вида — стар, нов и разширен.
Примери за стар:
![drop-down-1](https://cloud.githubusercontent.com/assets/1268290/2809919/9cccc82a-cd8c-11e3-8e79-302862979b39.png)
![drop-down-2](https://cloud.githubusercontent.com/assets/1268290/2809920/9fdc6962-cd8c-11e3-9051-65e64f67ba27.png)
![drop-down-5](https://cloud.githubusercontent.com/assets/1268290/2809923/c83b554e-cd8c-11e3-9f5d-ead4670f4391.png)
Пример за нов:
![drop-down-3](https://cloud.githubusercontent.com/assets/1268290/2809924/d07cd412-cd8c-11e3-9396-aa9b73f0c2ea.png)
Пример за разширен (от административния панел):
![drop-down-4](https://cloud.githubusercontent.com/assets/1268290/2809926/ea395f60-cd8c-11e3-98cf-0a1bc91ae26c.png)

Падащото меню за оценка на произведение и падащото меню за смяна на статус (в работното ателие) могат да се сменят с новия модел, а падащото меню за етикетите може да се смени с разширения модел за по-лесно търсене при добавянето на етикет.

**Comment by bmanolov** [comment]
Дреболия.
