### ISSUE TITLE
Ако в низа за търсене има интервал той играе ролята на процент

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#58]
Пример с [„нещо камък“](http://chitanka.info/search?q=%D0%BD%D0%B5%D1%89%D0%BE+%D0%BA%D0%B0%D0%BC%D1%8A%D0%BA).
Освен това не мога да схвана разликата между [„ни%та“](http://chitanka.info/search?q=%D0%BD%D0%B8%25%D1%82%D0%B0) и [„ни та“](http://chitanka.info/search?q=%D0%BD%D0%B8+%D1%82%D0%B0) при търсене.
За [„ни%та“](http://chitanka.info/search?q=%D0%BD%D0%B8%25%D1%82%D0%B0) се показва резултат „Треванян“ (най-вероятно, защото търси в „Истинско име“).

**Comment by bmanolov** [comment]
Нарочно е така. Това позволява намирането на Асен Г. Христофоров, като търсиш Асен Христофоров.

**Comment by haripetrov** [comment]
Добре.
