### ISSUE TITLE
 Съдържанието на книга не се формира коректно (спрямо секциите), а директно се изобразява шаблона

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#60]
Пример с http://chitanka.info/book/3939 и http://chitanka.info/book/4286:
![table-of-content](https://cloud.githubusercontent.com/assets/1268290/2809967/f3de84f2-cd8f-11e3-86ad-6f6be0dc5136.png)

Трябва заглавията на секциите да бъдат бъдат подредени, така че да отразяват йерархията

**Comment by bmanolov** [comment]
Дреболия.
