### ISSUE TITLE
Промяна на раздела „Информация“ за дадено произведение

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#64]
В раздела „Информация“ към произведение се извеждат данни за книжното издание, което предизвиква неприятно натрупване на излишна информация, ако произведението участва в повече от една книга.
Има и разминаване на логиката:
Произведение част от три книги: http://chitanka.info/text/1578
Произведение част от две книги: http://chitanka.info/text/16550
Трябва да се промени, така че да не излиза никаква информация за изданието/изданията.

**Comment by bmanolov** [comment]
В раздела „Информация“ се извежда информация само за книгата, от която е сканирано произведението. В общия случай това е само една книга, но при произведения, публикувани на части, там ще се покажат всички книги.

Според мен информацията не трябва да се скрива, а да се показва по различен начин, ако изглежда претрупано.

**Comment by haripetrov** [comment]
Добре, това също е вариант, но просто нямам за момента идея как това да стане.
