### ISSUE TITLE
Личните страници на потребителите съдържат в себе си два пъти лентата с връзки, както и основното меню

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#66]
Влизайки в коя да е лична страница (пример: [filthy](http://chitanka.info/user/filthy)) се вижда, че два пъти се съдържа лентата с връзки към различните подпроекти, както и съдържа два пъти навигационните менюта:
![filthy](https://cloud.githubusercontent.com/assets/1268290/5578322/ce61753e-902d-11e4-9e32-d2b411233a6a.png)

**Comment by bmanolov** [comment]
Поправено е.
