### ISSUE TITLE
Изгледът на списъка с книги на даден автор е счупен

### ISSUE THREAD

**Issue by haripetrov** [chitanka/chitanka#67]
Не знам как най-добре да го обясня освен с екранна снимка:
![chitanka-author-book-overview](https://cloud.githubusercontent.com/assets/1268290/6997640/a94a8922-dbb2-11e4-9278-099ba03e6e16.png)

**Comment by haripetrov** [comment]
Всичко е ток и жица.

**Comment by bmanolov** [comment]
Само така! :smile:
