### ISSUE TITLE
Премахване на всякакви референции към външни ресурси

### ISSUE THREAD

**Issue by zeridon** [chitanka/chitanka#73]
Здравейте,

При пускане на ново копие на съществуващата база на основната страница има известно количество външна информация (Купете Си, Прочетете, От литературните блогове). Това не е лошо но за съжаление включват елементи от външни източници.

За публичен сайт може би е приемливо но за скрита услуга (Tor Hidden service) или за нещо което се използва чисто вътрешно това е неприемливо.

Това води до изтичане на информация (referrer, visitor IP, cookies?).

Моля основната страница (поне в production варианта) да не съдърша елементи от трети страни (основно картинки) или като минимум да е ясно отбелязано че това се случва и как да бъдат изключени тези секции.

**Comment by bmanolov** [comment]
Секциите на началната страница вече могат да се конфигурират чрез файла `app/config/paramers.yml`. Предварителните настройки се намират в [`app/config/paramers_default.yml`](https://github.com/chitanka/chitanka/blob/master/app/config/parameters_default.yml#L106) – раздела `main.sections.`

Допълнително, можеш да посочиш и `allow_remote_wiki_article: false`, за да не се теглят статии от Уикипедия, когато се отвори страница на автор или преводач.
