### ISSUE TITLE
Проблем с пренасочване при сваляне на zip файл в Chrome

### ISSUE THREAD

**Issue by pistachio-consumer** [chitanka/chitanka#80]
При теглене на zip файлове от Библиотеката, Chrome засича некоректно вътрешно пренасочване от защитен HTTPS ресурс към незащитен такъв (HTTP). В резултат, браузъра показва съобщение за проблем със сигурността, пример:

![Chrome Security Warning](https://i.imgur.com/xEEo41l.png)

[Примерен линк](https://chitanka.info/text/3750/2#text-links) от Библиотеката с този проблем.
Този проблем не се наблюдава с Firefox :)

**Comment by bmanolov** [comment]
Пренасочването вече става с относителна схема (`//mirror.chitanka.info`) и би трябвало да работи без проблеми.
