### ISSUE TITLE
Грешка при изпълнение на update скрипта

### ISSUE THREAD

**Issue by basekat** [chitanka/chitanka#87]
При изпълнение на update скрипта, се получава следната грешка:

```
www-data@953aceba1c54:~/html$ /var/www/chitanka/bin/update 
13:35:39: Update started on 2022-06-10.
13:35:39: Pause for 0 seconds.
13:35:39: Executing source update...
sh: 1: LC_ALL=C git: not found
13:35:41: Executing content update...
```

**Comment by bmanolov** [comment]
Ето това е [конкретния ред, от който идва грешката](https://github.com/chitanka/chitanka/blob/master/app/Command/AutoUpdateCommand.php#L174).

Предполагам, че имаш git на машината.

Може би използвания синтаксис не важи в конктретната shell-програма. Това Bourne Shell ли е? Можеш ли да пробваш с bash?

**Comment by basekat** [comment]
Ползвам bash и имам git на машината:
![image](https://user-images.githubusercontent.com/16616757/174040384-910e6e53-df3c-42fe-8206-4ada2a9a9957.png)

Предполагам, че е от начина, по който php скрипта извиква командите.

**Comment by bmanolov** [comment]
Проблема би трябвало да се реши, ако се посочи пълния път до git, напр. `/usr/bin/git`.
