### ISSUE TITLE
chitanka-production.git chitanka.info branch is 18 commit ahead of master

### ISSUE THREAD

**Issue by basekat** [chitanka/chitanka#90]
Последните промени в chitanka-production.git са push-вани в chitanka.info branch-а. Като резултат chitanka-installer скрипта, който използва master branch-a, clone-ва остаряло копие на изходния код.

![image](https://user-images.githubusercontent.com/16616757/178532909-e0e7398e-3ce0-425b-8686-16f14fa14e0f.png)

**Comment by bmanolov** [comment]
Клона chitanka.info съдържа новата версия на софтуера. Скоро ще бъде включена и в основния клон.
